### ISSUE TITLE
Windows executables are built without the .exe extension

### ISSUE THREAD

**Issue by roxspring** [raydac/mvn-golang#1]
I've been playing around with the plugin on windows and noticed that the resulting binary doesn't get a .exe suffix.

**Comment by raydac** [comment]
in the first version I had implemented auto-extension but then removed it because extension can be very different and not every time user wants to get .exe, at present it is possible to define needed result extension through <resultName> (example from https://github.com/raydac/bkbin2wav/blob/master/gobkbin2wav/pom.xml)
```
<execution>
    <id>build-for-windows</id>
        <goals>
            <goal>build</goal>
         </goals>
         <configuration>
             <targetOs>windows</targetOs>
             <targetArch>386</targetArch>
             <resultName>${base.target.name}-windows386.exe</resultName>
         </configuration>
</execution>
```

**Comment by bogdanpredescu** [comment]
Indeed, in fact "go build/install -o output_binary_name" (which is what the plugin seems to do) does not add .exe on Windows so this is rather a go tools issue/thing. Can be changed either that way or using finalName maven tag however I guess then you need to add profiles for each target OS.

**Comment by raydac** [comment]
the result file may have too many variants of extension, even under windows thus it is responsibility of user to provide needed extension for his project, it is possible to make through profiles, the example https://github.com/raydac/bkbin2wav/blob/master/gobkbin2wav/pom.xml

**Comment by roxspring** [comment]
What variants of extensions? .exe is THE standard executable under Windows, as far as I'm aware no other platform requires extensions at all.  Fair enough, Windows uses additional extensions for batch files, dynamic link libraries, or unstructured <64K com binaries, but go doesn't create any of those so surely that's irrelevant!?
Of course go doesn't tack on a .exe when -o is used - you're explicitly telling it the file that you want written to, but normally when you tell go to build main.go and leave it to do something intelligent then it automatically adds the .exe suffix.
Sure it's possible to solve with multiple executions or profiles but that seems a pretty inelegant to me.

**Comment by raydac** [comment]
Go can build different file types and extension depends on -buildmode flag

**Comment by roxspring** [comment]
Huh! - was under the impression that go only built static .exe files, but it looks like -buildmode has changed that since 1.5!
Thanks for the info.

**Comment by bogdanpredescu** [comment]
wiki doc should be updated with <resultName> instead of <name> (which doesn't seem to take effect)
