### ISSUE TITLE
Cannot do crosscompiles because the plugin sets the GOBIN environment regardless

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [raydac/mvn-golang#10]
If you change the Go OS and Go Architecture values in the configuration, the go binary will try and do cross compiles. But, this will fail all the time due to the fact that GOBIN is set in the plugin as an environmentvariable as seen at:

https://github.com/raydac/mvn-golang/blob/master/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/AbstractGolangMojo.java#L1286

Resulting in:

[ERROR] ---------Exec.Err---------
[ERROR] go install: cannot install cross-compiled binaries when GOBIN is set

**Comment by raydac** [comment]
ok. will check
the latest version of Go SDK in usage?

**Comment by AlskiOnTheWeb** [comment]
Yes, 1.7.1

**Comment by raydac** [comment]
I can't reproduce such issue on my machine under Linux, so that I provided way to disable translation of GOBIN through pseudopath 'NONE', if provide such value then goBin will not be provided at all. 
```
<configuration>
   <goBin>NONE</goBin>
</configuration>
```

**Comment by raydac** [comment]
please clone the project and build the plugin snapshot and keep me informed about your case

**Comment by AlskiOnTheWeb** [comment]
OK, will do. One question...is there a maven repo hosting snapshots for this somewhere also? Thanks!

**Comment by raydac** [comment]
at present I don't have any public repository for snapshots, I will investigate on weekend how to organise it

**Comment by raydac** [comment]
I have tuned public maven snapshot repository, it can be used if to add
```
    <repositories>
      <repository>
        <id>coldcore.ru-snapshots</id>
        <name>ColdCore.RU Mvn Snapshots</name>
        <url>http://coldcore.ru/m2</url>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
        <releases>
          <enabled>false</enabled>
        </releases>
      </repository>
    </repositories>
```

**Comment by raydac** [comment]
did fix help?

**Comment by AlskiOnTheWeb** [comment]
Oh...sorry...I meant to get back to you on this. Yes, it definitely worked. We are now able to cross compile through the plugin. Thanks!
