### ISSUE TITLE
Is there a way to filter the list of source files that the plugin should build?

### ISSUE THREAD

**Issue by hoshposh** [raydac/mvn-golang#100]
## Overview

I have a number of projects that we are inheriting, that have a haphazard approach to where the Go source files reside. In those projects the approach that the team member has been using to ensure that only source code that is needed is to issue an `go build` and list the source files to include.

Is there a way to configure the `mvn-golang-wrapper` plugin to perform a build and supply a list of files to use in the build?

Over time we will be making efforts to refine the project in question but in the interim allowing the plugin to work alongside the conventional Go build approaches that other team members might be using.

**Comment by raydac** [comment]
wrapper just wraps calls for golang but I think there are pair ways to play with lists
1. make copy of required source files into special folder during build (for instance with copy-rename-maven-plugin) and provide the new folder as the source folder
2. use preprocessor plugin and mark non-needed source files as excluded for build like I have [in example](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-preprocessing)

**Comment by hoshposh** [comment]
Thanks for the ideas @raydac, the 2nd one was what I hoped might be a solution, I just needed an example.
