### ISSUE TITLE
Unrecognized ARCH aarch64 on a Arm Mac

### ISSUE THREAD

**Issue by hoshposh** [raydac/mvn-golang#103]
## Overview

When building a project on an arm based Mac I see the following error:

```console
Exception in thread "main" java.lang.AssertionError: Can't recognize ARCH: aarch64
```

It seems that there is an assumption about the arch type, which should be `arm64`.

### Workaround

I can set the `arch` configuration property to `arm64`:

```xml
      <plugin>
        <groupId>com.igormaznitsa</groupId>
        <artifactId>mvn-golang-wrapper</artifactId>
        <extensions>true</extensions>
        <configuration>
          <arch>arm64</arch>
        </configuration>
        .
        .
      </plugin>
```

**Comment by raydac** [comment]
it is very strange, because function processing the architecture has branch for the type
https://github.com/raydac/mvn-golang/blob/c29ce5127e8adf5b04011553e45020c5f0de5ee3/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/utils/SysUtils.java#L53

**Comment by hoshposh** [comment]
> it is very strange, because function processing the architecture has branch for the type
> 
> https://github.com/raydac/mvn-golang/blob/c29ce5127e8adf5b04011553e45020c5f0de5ee3/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/utils/SysUtils.java#L53

Apologies, I must have been using an earlier release. Sure enough the `2.3.10` release correctly identifies the architecture. So, I am closing the issue. Sorry once again! 😊
