### ISSUE TITLE
maven multi modules with dependency management

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#12]
Possible to layout maven go modules like this ??

    common
    app-1
    app-2

both app-1 and app2 are using common

**Comment by raydac** [comment]
I made [example for such case](https://github.com/raydac/mvn-golang/releases/download/2.1.2/mvn-golang-multimodule-example.zip), take a look please

**Comment by dantran** [comment]
awesome!!!

**Comment by dantran** [comment]
the example will not survive multithreaded build.  You will need to make both app1 and app2 to depends on   common.pom

**Comment by raydac** [comment]
good point, thanks!

**Comment by dantran** [comment]
agree, both app1 and app2 does do not depend on output binary from common, but sources only
