### ISSUE TITLE
goBin is not hornor

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#13]
Go: 1.7.1
mvn: 3.3.9
this plugin: 2.1.2 (ie latest)

I am trying to configure goBin to use ${project.build.directory}/bin
  
    <configuration>
        <goBin>${project.build.directory}${file.separator}bin</goBin>
        [...]
    </configuration>

the outputs always go to ${project.build.directory}

**Comment by raydac** [comment]
am I right that you trying to redefine the output directory for build result? if so then it is defined in `    <directory>${basedir}${file.separator}bin</directory>
` , and goBin allows just to define $GOBIN environment variable but build command is called with direct -o parameter to place result into maven result folder defined through `<directory>` (mvn-golang build mojo has special parameter `resultFolder` which default value is ${project.build.directory})

**Comment by dantran** [comment]
best practice not to change project/build/directory since it impacts other plugins in the build lifecycle
this plugin goBin has default value to ${proejct.build.directory},  the plugin user should be able to override goBin settings

**Comment by raydac** [comment]
exactly, but mvn-golang plugin changes the lifecycle totally because it is not java based one, thus plugins which are sensetive to java lifecycle and environment have to be moved into another module of same project and they will be processed in right java lifecycle

**Comment by dantran** [comment]
this not about java code,   it can be other plugins. For example my msi-maven-plugin also uses that global config too :-)

**Comment by raydac** [comment]
standard lifecycle processors will not be working because just will not find needed content in golang project and will not be able to install and deploy anything, the only way to separate plugins in different modules of the same project imho like as in [multimodule example](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-multimodule)

**Comment by dantran** [comment]
your last comment addressing my install/deploy issue?  or about goBin.  If user are not allowed to alter goBin may be best to remove it from plugin's  configuration. 

Would you accept PR? :-)

**Comment by raydac** [comment]
goBin just allows to define $GOBIN during build process, it was added for [the request](https://github.com/raydac/mvn-golang/issues/10), it can be disabled for working process just with `<goBin>NONE</goBin>` and plugin will stop processing of value

**Comment by dantran** [comment]
i think i can use  resultFolder.  you may want to update goBin to refer user to resultFolder settings

**Comment by raydac** [comment]
the default value for `resultFolder` is `${project.build.directory}` and default value for `goBin` is also `${project.build.directory}` , the `${project.build.directory}` can be changed through through `    <directory>${basedir}${file.separator}bin</directory>
` which defines the property
