### ISSUE TITLE
mvn-golang package swallows other packagings

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#14]
my mvn-golang module produces multiple golang binaries.  then I use maven-assembly-plugin to tar them up and have maven to install and deploy to maven repo. 

However,  this plugin seems to swallow my assembly. please add default maven install and deploy to its build lifecycle

existing install/deploy phase currently bind to

              <install>com.igormaznitsa:mvn-golang-wrapper:mvninstall</install>
              <deploy>com.igormaznitsa:mvn-golang-wrapper:install</deploy>

**Comment by raydac** [comment]
could you provide the pom.xml where you call assembly plugin?

**Comment by dantran** [comment]
Do you have an email i can send to?

**Comment by raydac** [comment]
I have updated multi-module test and provided [assembing of results through maven assembly](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-multimodule), looks workings, take a look please
my email rrg4400@gmail.com

**Comment by dantran** [comment]
that works fi you using multi module, but I am locked using using single maven build to produce all Go binaries, and assemble them up to deploy to maven.  this plugin removes the default install and deploy executions

**Comment by dantran** [comment]
sent you my pom. Thanks

**Comment by dantran** [comment]
You really want to add those 2 extra plugin configuratoin in my pom? :-1: 

but maven standard installer is also just a plugin which can be included into the process manually through some like

<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.4</version/>
          <executions>
            <execution>
              <id>install1</id>
              <phase>package</phase>
              <goals>
                <goal>install-file</goal>
              </goals>
              <configuration>
                <file>lib/your-artifact-1.0.jar</file>
                <groupId>org.some.group</groupId>
                <artifactId>your-artifact</artifactId>
                <version>1.0</version>
                ... other properties
              </configuration>
            </execution>
            <execution>
              <id>install2</id>
              <phase>package</phase>
              <goals>
                <goal>install-file</goal>
              </goals>
              ... etc

            </execution>
            ... other executions
          </executions>
</plugin>

in case of project type mvn-golang, standard installer just will not find needed artifact and in manual installation you can provide needed stuff through parameters

On 11/08/2016 09:02 AM, Dan Tran wrote:
the executions of my assembly and msi plugins do work, but its outputs
which I 'attach' to maven session are not get installed to local repo
and to my internal maven repository.

This is mainly due to your mvn-golang package removes
maven-install-plugin and maven-deploy-plugin from the build lifecycle

-D

On Mon, Nov 7, 2016 at 10:45 PM, Igor Maznitsa <rrg4400@gmail.com
<mailto:rrg4400@gmail.com>> wrote:

    golang wrapper just replaces default install and deploy tasks in
    maven lifecycle, but phases still the same and your plugins will be
    called anyway as expected, which errors they generate? could you
    show log?



    On 11/08/2016 08:36 AM, Dan Tran wrote:

        By default, it builds native Go binaries

        with msi profile, it builds windows binary, and then create MSI
        and a
        tar ball

        Thanks for this great plugin

        -Dan



    --
    Igor Maznitsa

    email: rrg4400@gmail.com <mailto:rrg4400@gmail.com>
    http://www.igormaznitsa.com

**Comment by raydac** [comment]
if your **golang project** produces also some java artifact (like jar) which should be installed  into maven repository then it is a normal way to make installation of java artifacts into maven reprository manually, on start of my usage of maven I also made such uber-pom errors, it is just inappropriate usage of maven and as result I had hack over hack (I was trying to test developed plugin in the same single module project for instance), the right maven way is to make multi-module project

**Comment by dantran** [comment]
i think it does no harm to have 2 executions per install/depoy phase

    <install>
         com.igormaznitsa:mvn-golang-wrapper:mvninstall,
         org.apache.maven.plugins:maven-install-plugin:install
    </install>
     <deploy>
          com.igormaznitsa:mvn-golang-wrapper:install,
          org.apache.maven.plugins:maven-deploy-plugin:deploy
     </deploy>

**Comment by raydac** [comment]
if to add standard install and deploy into lifecycle for `<type>mvn-golang</type>` then standard plugins will be looking for artifact to install, in case of Java it is jar, and what to install in case of golang?

**Comment by dantran** [comment]
I think you already using .mvn-golang. You can attach anything to maven session.  
felix-maven-plugin has packaging type as 'bundle' but it deploys .jar

**Comment by raydac** [comment]
maven is java oriented one and if my plugin would produce jar then there would not be any problems, the maven install would perfectly processing that, but in golang we don't have any cross-platform artifact like jar but platform-dependent executable as result of work and it would be strange to install such platform-dependent thing into maven repository, so that I made own implementation of install which packs sources and resources and install them as archive into repository, I see the only workaround - to use custom install if maven plugin generates java artifact in golang module

**Comment by dantran** [comment]
maven by default support java, but it does not mean you cant extended and still working in harmony with other plugins here is an example at native-maven-plugin
![image](https://cloud.githubusercontent.com/assets/705836/20

092984/9ad03992-a54f-11e6-9bd9-b90b4d0080bf.png)

again i dont see any issue with both yours and standard can coexist. and make it easier for user :-)

**Comment by raydac** [comment]
it needs experiments,  I have tried to implements both tasks in maven install phase
```
 <install>com.igormaznitsa:mvn-golang-wrapper:mvninstall,org.apache.maven.plugins:maven-install-plugin:install</install>
```
but in the case golang project throws error (as expected)
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project mvn-golang-examples-helloworld: The packaging for this project did not assign a file to the build artifact
```
maven desires artifact, the question what could play such role if golang doesn't egenrate any cross-platform artifact

**Comment by dantran** [comment]
Thanks for considering a fix 

    <install>
         com.igormaznitsa:mvn-golang-wrapper:install,
         com.igormaznitsa:mvn-golang-wrapper:mvninstall,
         org.apache.maven.plugins:maven-install-plugin:install
    </install>
   <deploy>
         org.apache.maven.plugins:maven-deploy-plugin:deploy
   </deploy>

You will need a flag to allow user skip com.igormaznitsa:mvn-golang-wrapper:install

**Comment by dantran** [comment]
replace mvn-install with( note, you must not remove the file, that is where the error coming from)

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
      try {
        final File archive = compressProjectFiles();
        Artifact artifact = this.project.getArtifact();
        artifact.setFile( archive );
      } catch (IOException ex) {
        throw new MojoExecutionException("Detected unexpected IOException, check the log!", ex);
      }
    }

**Comment by raydac** [comment]
what do you mean as `replace mvn-install`? what is `compressProjectFiles`?
as I see you forked project, could you make the change and demonstrate how such approach will be working and back compatibility will be saved (because some people use the plugin and they will be unhappy if changes in lifecycle will break their projects)

**Comment by dantran** [comment]
here is my initial change 
![image](https://cloud.githubusercontent.com/assets/705836/20112860/cadd8470-a5a2-11e6-9cc7-675a4ac45fa6.png)

**Comment by raydac** [comment]
looks good but multi-module test is red

**Comment by dantran** [comment]
I fixed the  test, naming   artfiactId as app-1 confused maven, it must be app1

**Comment by raydac** [comment]
maven allows to have `-` in in `artifactId`
```
artifactId is the name of the jar without version. If you created it then you can choose whatever name you want with lowercase letters and no strange symbols. If it's a third party jar you have to take the name of the jar as it's distributed.
eg. maven, commons-math
```

**Comment by dantran** [comment]
not with   -1, -2, etc at the end of artifactId

**Comment by raydac** [comment]
tried even manually create java project with `some-1` artifact name and compile and install, there is no problems if to create jar artifact with maven 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.igormaznitsa</groupId>
    <artifactId>some-1</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
</project>
```
```
Installing /home/igorm/Temp/some-1/pom.xml to /home/igorm/.m2/repository/com/igormaznitsa/some-1/1.0-SNAPSHOT/some-1-1.0-SNAPSHOT.pom
```

**Comment by dantran** [comment]
it breaks when you start using multiple modules with dependencies.  Best not to confuse Maven

**Comment by raydac** [comment]
I have tested a java multimodule project, the project contains  modules named `some-1` `some-2`, maven works well with such names, I have even added dependency in `some-2` to `some-1` modue, maven builds and install without problems

**Comment by dantran** [comment]
could you post your build somewhere?. I have run into this before that is why would never name my artifactid that way.  Do you think Go maven user would name artifactid that way? it is not likely

**Comment by dantran** [comment]
I reverted the example back.  The error is from common module, it has no artifact and maven fail it at install time. So I disable 'common' module

**Comment by raydac** [comment]
`common` contains tests and if to disable it then tests of the module will not be processed

**Comment by dantran** [comment]
Ok, I reenable common module but need to enable mvn-install to prepare artifact
