### ISSUE TITLE
go get -t -v .

### ISSUE THREAD

**Issue by pritishmishra** [raydac/mvn-golang#16]
Hi
I am unable to do a "go get -t -v ." in the source directory of my project.
However, the actual go installed on my machine works fine with this.
But when I try to build using mvn and pom.xml, it gets stuck at this get dependecy.
I am attaching the snippet of my pom.xml for your reference.
Please help! 

```xml
<execution>
            <id>dependency11</id>
            <goals>
            <goal>get</goal>
            </goals>
         <configuration>
           <buildFlags>
                <flag>-t</flag>
                <flag>-v</flag>
           </buildFlags>
           <packages>
                <package>.</package>
            </packages>
      </configuration>
</execution>
```

**Comment by raydac** [comment]
Hi
what message do you have in console?

**Comment by pritishmishra** [comment]
Hii
I believe I am using go1.7.3. I am not getting any message related to this dependency. Attaching a screenshot of the point where the execution is stuck.
![screenshot131](https://cloud.githubusercontent.com/assets/5333020/21644814/6ae704f2-d2b5-11e6-99d2-e7b1437eb189.PNG)

**Comment by raydac** [comment]
try "./..." instead of "."

**Comment by raydac** [comment]
made some test to load test dependencies https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-testing , didn't get issues in my machine

**Comment by pritishmishra** [comment]
Can you please check with "." instead of "./..."?
It picks up some unwanted dependencies when I use "./..."

**Comment by raydac** [comment]
with '.' my test doesn't work because './...' checks recursively all packages and load dependencies, and '.' only root package, if you don't want to get all dependencies then may be in your case just define directly names of packages which you want to get?
