### ISSUE TITLE
mvn deploy  make    can't load package: package

### ISSUE THREAD

**Issue by Seven-zhang** [raydac/mvn-golang#17]
execute  command  `mvn clean deploy` ,output mistake 
[ERROR] can't load package: package .: no buildable Go source files in /work/go-pro/src ,
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.574 s
[INFO] Finished at: 2017-02-07T15:22:26+08:00
[INFO] Final Memory: 40M/455M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.2:install (default-install) on project oss-eureka-sidecar: Process exit code : 1 -> [Help 1]

my app exist /work/go-pro/src/github/test/main.go
how do work?

**Comment by raydac** [comment]
it looks like that you provide some wrong package, golang complains `can't load package: package .`
could you provide your pom.xml?

**Comment by Seven-zhang** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.yirendai.oss.environment</groupId>
    <artifactId>oss-eureka-sidecar</artifactId>
   <version>1.0</version>
    <packaging>mvn-golang</packaging>

    <properties>
        <mvn-golang-wrapper.version>2.1.2</mvn-golang-wrapper.version>
        <assembly.version>3.0.0</assembly.version>
        <goVersion>1.7.3</goVersion>
    </properties>

    <build>
        <sourceDirectory>${basedir}${file.separator}src</sourceDirectory>
        <directory>${basedir}${file.separator}bin</directory>
        
        

        <plugins>
            <plugin>
                <groupId>com.igormaznitsa</groupId>
                <artifactId>mvn-golang-wrapper</artifactId>
                <version>${mvn-golang-wrapper.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <addToGoPath>
                        <folder>${project.basedir}${file.separator}bin</folder>
                    </addToGoPath>
                    <autofixGitCache>true</autofixGitCache>
                    <command>theCommand</command>
                    <goVersion>${goVersion}</goVersion>
                    <verbose>true</verbose>
                </configuration>
                <executions>
                    <execution>
                        <id>default-get</id>
                        <configuration>
                            <buildFlags>
                                <flag>-u</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github.com/smartystreets/goconvey</package>
                                <package>github.com/bmizerany/assert</package>
                            </packages>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-seelog</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/cihub/seelog</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v2.6</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-simplejson</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/bitly/go-simplejson</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v0.5.0</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-ini</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/go-ini/ini</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v1.21.1</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-yaml</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <buildFlags>
                                <flag>-u</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github.com/go-yaml/yaml</package>
                            </packages>
                            <branch>v2</branch>
                        </configuration>
                    </execution>

                    <execution>
                        <id>default-test</id>
                        <configuration>
                            <buildFlags>
                                <flag>-v</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-build</id>
                        <configuration>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github.com/test</package>
                            </packages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${assembly.version}</version>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>conf/assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by Seven-zhang** [comment]
<groupId>com.hua</groupId>
   <artifactId>test</artifactId>
  <version>1.0</version>
   <packaging>mvn-golang</packaging>

 <properties>
        <mvn-golang-wrapper.version>2.1.2</mvn-golang-wrapper.version>
        <assembly.version>3.0.0</assembly.version>
        <goVersion>1.7.3</goVersion>
    </properties>

    <build>
        <sourceDirectory>${basedir}${file.separator}src</sourceDirectory>
        <directory>${basedir}${file.separator}bin</directory>
        
        

        <plugins>
            <plugin>
                <groupId>com.igormaznitsa</groupId>
                <artifactId>mvn-golang-wrapper</artifactId>
                <version>${mvn-golang-wrapper.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <addToGoPath>
                        <folder>${project.basedir}${file.separator}bin</folder>
                    </addToGoPath>
                    <autofixGitCache>true</autofixGitCache>
                    <command>theCommand</command>
                    <goVersion>${goVersion}</goVersion>
                    <verbose>true</verbose>
                </configuration>
                <executions>
                    <execution>
                        <id>default-get</id>
                        <configuration>
                            <buildFlags>
                                <flag>-u</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github.com/smartystreets/goconvey</package>
                                <package>github.com/bmizerany/assert</package>
                            </packages>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-seelog</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/cihub/seelog</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v2.6</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-simplejson</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/bitly/go-simplejson</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v0.5.0</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-ini</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <packages>
                                <package>github.com/go-ini/ini</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                            <tag>v1.21.1</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dependency-yaml</id>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <buildFlags>
                                <flag>-u</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github.com/go-yaml/yaml</package>
                            </packages>
                            <branch>v2</branch>
                        </configuration>
                    </execution>

                    <execution>
                        <id>default-test</id>
                        <configuration>
                            <buildFlags>
                                <flag>-v</flag>
                            </buildFlags>
                            <goVersion>${goVersion}</goVersion>
                        </configuration>
                    </execution>

                    <execution>
                        <id>default-build</id>
                        <configuration>
                            <goVersion>${goVersion}</goVersion>
                            <packages>
                                <package>github/test</package>
                            </packages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${assembly.version}</version>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>conf/assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by Seven-zhang** [comment]
<groupId>com.hua</groupId>
    <artifactId>test</artifactId>
   <version>1.0</version>
    <packaging>mvn-golang</packaging>

**Comment by Seven-zhang** [comment]
<groupId>com.hua</groupId>
    <artifactId>test</artifactId>
    <version>1.0</version>
    <packaging>mvn-golang</packaging>

**Comment by raydac** [comment]
pom.xml looks good, if you want I can try to build on my machine if you send  project zip to rrg4400@gmail.com

**Comment by raydac** [comment]
try to provide path to your main package
```
<configuration>
		<packages>
            		<package>github.com/yirendai/yrd-environment/oss-eureka-sidecar/sidecar</package>
          	</packages>
               

               <addToGoPath>
                    <folder>${project.basedir}${file.separator}bin</folder>
                </addToGoPath>
                <autofixGitCache>true</autofixGitCache>
                <command>theCommand</command>
                <goVersion>${goVersion}</goVersion>
                <verbose>true</verbose>
            </configuration>
```

**Comment by Seven-zhang** [comment]
build is success, but   [ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.2:install (default-install)

**Comment by Seven-zhang** [comment]
thanks your help, my issue have solve,  in pom.xml   add :
<execution><id>default-install</id><configuration><goVersion>${goVersion}</goVersion><packages><package>github.com/yirendai/yrd-environment/oss-eureka-sidecar/sidecar</package></packages></configuration></execution>

that is ok!   raydac    can you delete  comment  with "yirendai" flag? because yirendai is company name,   thanks!



At 2017-02-07 20:08:16, "Igor Maznitsa" <notifications@github.com> wrote:


try to provide path to your main package

<configuration>
		<packages>
            		<package>github.com/yirendai/yrd-environment/oss-eureka-sidecar/sidecar</package>
          	</packages>
               

               <addToGoPath>
                    <folder>${project.basedir}${file.separator}bin</folder>
                </addToGoPath>
                <autofixGitCache>true</autofixGitCache>
                <command>theCommand</command>
                <goVersion>${goVersion}</goVersion>
                <verbose>true</verbose>
            </configuration>

**Comment by Seven-zhang** [comment]
add                    <execution>
                        <id>default-install</id>
                        <configuration>
                            <packages>
                                <package>github/test</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                        </configuration>
                    </execution>

**Comment by Seven-zhang** [comment]
add pom.xml
                    <execution>
                        <id>default-install</id>
                        <configuration>
                            <packages>
                                <package>github/test</package>
                            </packages>
                            <goVersion>${goVersion}</goVersion>
                        </configuration>
                    </execution>

**Comment by raydac** [comment]
so you have resolved the issue?

**Comment by Seven-zhang** [comment]
yes ,thanks

**Comment by raydac** [comment]
ok, I have replaced text in the comment
