### ISSUE TITLE
Could not set goPath in Linux from pom.xml

### ISSUE THREAD

**Issue by Vigneshr6** [raydac/mvn-golang#19]
Hi,
this below code sets 'goPath' in windows.but in linux it doesn't.
```
				<groupId>com.igormaznitsa</groupId>
				<artifactId>mvn-golang-wrapper</artifactId>
				<version>2.1.1</version>
				<extensions>true</extensions>
				<configuration>
					<target>${basedir}/new</target>
					<goVersion>1.8</goVersion>
					<env>
					<goPath>${basedir}/lib</goPath>
					</env>
					<useEnvVars>true</useEnvVars>
				</configuration>
```

**Comment by Vigneshr6** [comment]
Linux is case sensitive.
I changed this `<goPath>${basedir}/lib</goPath>`  to `<GOPATH>${basedir}/lib</GOPATH>`
Then I worked

**Comment by raydac** [comment]
anyway your configuration looks a bit strange
the flag `<useEnvVars>` tells plugin to use environment variables if they presented, but there is just `<goPath>` parameter of the plugin
and if you want use libraries and add extra stuff into GOPATH then you just could use 
```
<addToGoPath>
    <myLib>${basedir}/lib</myLib>
</addToGoPath>
```

**Comment by Vigneshr6** [comment]
ok
I will use this method
Thanks @raydac
