### ISSUE TITLE
"mvn deploy" doesn't attempt to deploy an artifact to the maven repository

### ISSUE THREAD

**Issue by roxspring** [raydac/mvn-golang#2]
Running `mvn deploy` I fully expect to have the results of my maven build deployed into our Artifactory but don't get that result with the golang extension present.  To be honest, when running `mvn install` I full expect to get the binary in my ~/.m2/repository/ too but that doesn't happen here either.  I understand that its' not necessarily straight forward when trying to harmonize the verbs of the two build systems but these seem pretty major departures from the maven tradition!

**Comment by raydac** [comment]
`mvn deploy` wraps `go install` command, it would be interesting to make deploying also into maven repository but I have not any idea what to deploy in the case, to deploy executable result file? but such artefact can't be used as dependency in future

**Comment by raydac** [comment]
since 2.1.0 it will be creating artifact in local repository for `mvn install`

**Comment by roxspring** [comment]
Cool - thanks!
