### ISSUE TITLE
setting a custom name for the build artifact

### ISSUE THREAD

**Issue by aguy** [raydac/mvn-golang#20]
I tried to use finalName to set a custom artifact name like this : 
```<finalName>${project.artifactId}-${project.version}-${git.branch}-${git.commit.id.abbrev}</finalName>```

git.* variables are made available by a plugin called pl.project13.maven, but whatever I tried, the go build cmdline doesn't interpret the variables and the output file ends up being something like this : 
my_project-1.0-SNAPSHOT-${git.branch}-${git.commit.id.abbrev}

Any idea how to achieve what I want ?

**Comment by raydac** [comment]
may be __pl.project13.maven__ injects its variables too late, in the case you could try to define final name of the artifact directly in build mojo (by default it uses final name)
```
<executions>
    <execution>
        <id>default-build</id>
        <configuration>
           <resultName>${project.artifactId}-${project.version}-${git.branch}-${git.commit.id.abbrev}</resultName>
        </configuration>
     </execution>
</executions>
```

**Comment by raydac** [comment]
did it help?

**Comment by aguy** [comment]
I finally upgraded the pl.project13.maven to a latest version and it worked.

**Comment by raydac** [comment]
cool! thank you for the info
