### ISSUE TITLE
how to lock a Go build to a master ref?

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#21]
Hi my build needs to lock down an external project at git hub which does not provide tag ( https://github.com/hashicorp/go-plugin/issues/30).  is there a way in this plugin to lock the source to  a ref?

**Comment by dantran** [comment]
looks like i can use   'revision' param using Git hash value??

**Comment by raydac** [comment]
thank you very much for your question, I have found bug in processing of revision value and fixed it, so in your case you exactly can use <revision>hash</revision> (since 2.1.4-SNAPSHOT), the current verion published in maven central can't process the value correctly

**Comment by dantran** [comment]
wow, thanks for fixing this.  Should i specify both   branch and revision? or revision is sufficient

**Comment by raydac** [comment]
revision containing hash should be enough

**Comment by dantran** [comment]
for some reason, build is failing for me 

[INFO] --- meta-checker:1.1.2:check (default) @ mvn-golang-wrapper ---
[INFO]   __  __  ____  ____   __
[INFO]  (  \/  )( ___)(_  _) /__\
[INFO]   )    (  )__)   )(  /(__)\
[INFO]  (_/\/\_)(____) (__)(__)(__)
[INFO] https://github.com/raydac/meta
[INFO]
[INFO] ................................
[INFO] Folder to look for classes : C:\views\dev\tools\maven\mvn-golang\mvn-golang-wrapper\target\classes
[INFO] ................................
[ERROR] Detected class version violator, version 8.0 at C:\views\dev\tools\maven\mvn-golang\mvn-golang-wrapper\target\classes\com\igormaznitsa\mvngolang\AbstractGolangMojo$1.class
[INFO] ................................
[INFO] Processed classes : 1
[INFO] Detected annotations : 0
[INFO] Detected To-Do : 0
[INFO] Detected risks : 0
[INFO] Detected experimental : 0
[INFO] Total warnings : 0
[ERROR] Total errors : 2
[INFO] ................................
[INFO] Total spent time : 00:00:00.093
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

I am using mvn 3.5 and java 8

**Comment by dantran** [comment]
encounter this [ERROR] fatal: Unable to find remote helper for 'https'  during  Go get

**Comment by raydac** [comment]
which OS do you use to build project?

**Comment by dantran** [comment]
i am using windows 10

**Comment by dantran** [comment]
ok, it got it thru, but i dont think it honor the revision.  

here is my execution block

          <execution>
            <id>get-go-plugin</id>
            <phase>generate-sources</phase>
            <configuration>
              <autofixGitCache>true</autofixGitCache>
              <packages>
                <package>github.com/hashicorp/go-plugin</package>
              </packages>
              <revision>c94b6fcef0368c6193c5e5260393686e95e5c517</revision>
            </configuration>
            <goals>
              <goal>get</goal>
            </goals>
          </execution>

**Comment by raydac** [comment]
I made some fixes, please, try the current version, it looks like that the issue was that my CVS operations were executed too late

**Comment by dantran** [comment]
no luck  so far.  I need to describe a little bit more.   

Out Go app build started to fail yeterday due to change at hashicop/go-plugin master, this leads me this path try to see of can lock it to a revision before the breakage.  Here is our Go get settings

         <execution>
            <id>get-go-plugin</id>
            <phase>initialize</phase>
            <configuration>
              <autofixGitCache>true</autofixGitCache>
              <packages>
                <package>github.com/hashicorp/go-plugin</package>
              </packages>
              <revision>c94b6fcef0368c6193c5e5260393686e95e5c517</revision>
            </configuration>
            <goals>
              <goal>get</goal>
            </goals>
          </execution>

          <execution>
            <id>default-get</id>
            <phase>generate-sources</phase>
            <configuration>
              <autofixGitCache>true</autofixGitCache>
              <packages>
                <package>github.com/gorilla/mux</package>
                <package>github.com/go-ole/go-ole</package>
                <package>github.com/fsnotify/fsnotify</package>
                <package>github.com/kardianos/service</package>
                <package>github.com/spf13/viper</package>
                <package>github.com/spf13/pflag</package>
                <package>golang.org/x/sys/windows/registry</package>
                <package>github.com/go-resty/resty</package>
                <package>github.com/satori/go.uuid</package>
                <package>gopkg.in/natefinch/lumberjack.v2</package>
              </packages>
            </configuration>
          </execution>

So far i am seeing  the same error at our build side.

**Comment by raydac** [comment]
it is possible that the issue that Go has compiled version of the module in its cache, could you try to add `<enforceDeletePackageFiles>true</enforceDeletePackageFiles>` into get configuration for github.com/hashicorp/go-plugin? it will delete compiled and source packages for the dependency before get

**Comment by raydac** [comment]
also git should recognizing revision hash  provided as `<branch>hash</branch>`

**Comment by dantran** [comment]
good news my build is good again by lock go-plugin a couple days backward.  It works with both branch=hash and revision=hash.  Very much appreciated the helps

**Comment by raydac** [comment]
cool! thank you for the info!
I added  [some tests for git cvs](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/test-cvs)

**Comment by dantran** [comment]
looking forward to pick up 1.2.4 release

**Comment by raydac** [comment]
I hope to public it in the weekend, now adding more tests for CVS systems

**Comment by raydac** [comment]
2.1.4 has been published in maven central and should be accessible
