### ISSUE TITLE
Weird artifact generated when trying to compile a github package.

### ISSUE THREAD

**Issue by dtromb** [raydac/mvn-golang#22]
I'm trying to compile a github package, which otherwise woks fine, using mvn-golang-wrapper:

               <execution>
                        <id>build-rice</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <name>rice</name>
                            <resultName>rice</resultName>
                            <goPath>${basedir}/src/main/go</goPath>
                            <sources>${basedir}/src/main/go</sources>
                            <goVersion>1.8.1</goVersion>
                            <packages>
                                <package>github.com/GeertJohan/go.rice</package>
                            </packages>
                        </configuration>
                    </execution>

The source is already in my project directory, so there is no dependency management going on here.

The build mojo executes: 

          Build mode : default
          Cached SDK detected : /home/dtrombley/.mvnGoLang/go1.8.1.linux-amd64
          Executable file detected : /home/dtrombley/.mvnGoLang/go1.8.1.linux-amd64/bin/go
          Prepared command line : bin/go build -buildmode=default -o                     
          /home/dtrombley/NetBeansProjects/MyProject//target/rice github.com/GeertJohan/go.rice
          GoLang project sources folder : /home/dtrombley/NetBeansProjects/MyProject/src/main/go

          ....Environment vars....
           $GOROOT = /home/dtrombley/.mvnGoLang/go1.8.1.linux-amd64
           $GOPATH = /home/dtrombley/NetBeansProjects/MyProject/src/main/go:/home/dtrombley/MyProject/src/main/java
           $GOBIN = /home/dtrombley/NetBeansProjects/MyProject/target
           $PATH = /usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3:/usr/local/java/bin:~/netbeans-8.1/bin:/home/dtrombley/go/root/bin:/home/dtrombley/.mvnGoLang/go1.8.1.linux-amd64/bin:/home/dtrombley/NetBeansProjects/MyProject/target
           ........................
           The Result file has been successfuly created : /home/dtrombley/NetBeansProjects/MyProject/target/rice

But then, the thing that was generated is broken and weird:

     dtrombley@snow ~/NetBeansProjects/MyProject/target $ ./rice
     ./rice: line 1: syntax error near unexpected token `newline'
     ./rice: line 1: `!<arch>'
     dtrombley@snow ~/NetBeansProjects/MyProject/target $ file rice
     rice: current ar archive     
     dtrombley@snow ~/NetBeansProjects/MyProject/target $ ar -t rice 
     __.PKGDEF
     _go_.o

Trying to build other packages works just fine.  Could it be the '.' character in the package name?

**Comment by dtromb** [comment]
(and _go_.o is not an object file, but an object file with some ASCII text tacked on the front of it:

     go object linux amd64 go1.8.1 X:framepointer
     build id "ef7ce4554189e84f61578bf8b04f485b31cda2de"
     ----
     <object file binary>
)

**Comment by raydac** [comment]
try to not redefine goPath totally, if you want to provide some extra path in goPath then you should use `<addToGoPath>` section and in your case it will be
```
<addToGoPath>
  <path>${basedir}/src/main/go</path>
</addToGoPath>
```
may be replacement of goPath broke build process

**Comment by dtromb** [comment]
Ah, it looks like what's going on is I wanted `<package>github.com/GeertJohan/go.rice/rice</package>` instead.   The package `github.com/GeertJohan/go.rice` is not named 'main', so `go build` produces nothing.   

I tested this with some other package lists without a 'main' and the same thing happens.  Should there be an error to the effect of "no main package in package list" or something like that, when there isn't, instead of the current behavior?

**Comment by raydac** [comment]
my plugin is just a wrapper and I check result of execution of golang tool, if it doesn't see error, then and my wrapper thinks that all is ok
there is special flag for golang build  `buildmode` where you can define behavior, by default it works in automatic mode and as written in description `Listed main packages are built into executables and listed non-main packages are built into .a files`, there is mode `exe` - `Build the listed main packages and everything they import into executables. Packages not named main are ignored.`, you can provide value by the plugin as `<buildMode>exe</buildMode>`

**Comment by raydac** [comment]
do you have found solution for the case?

**Comment by dtromb** [comment]
I don't think there is actually any issue here any more - you've explained why it's building .a and that makes sense.   It was confusing from a UI standpoint since I'm used to just running `go build` - which of course builds the .a just the same /but then puts it in a totally different place by default/.     So go ahead and close this, there's no defect.
