### ISSUE TITLE
go1.9 not downloadable

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#24]
https://github.com/golang/go/issues/21667  mentions the list is truncated

**Comment by dantran** [comment]
looks like it is fixed in latest mvngolang 2.1.6

**Comment by raydac** [comment]
i have "fixed" it since 2.1.6, now if SDK not in list, plugin makes some guess about type of archive and load distributive without list, but if any problem with such approach then it is possible directly define URL of Golang SDK through `<sdkDownloadUrl></sdkDownloadUrl>`

**Comment by dantran** [comment]
it works. I'll close this issue.  Thanks for explanation

**Comment by raydac** [comment]
anyway I made some improving in 2.1.7 to load SDK list, thank you very much for info and link to discussion about work with the sdk list
