### ISSUE TITLE
Malicious executable x.exe inside the downloaded Go SDK of go1.9.1.win32

### ISSUE THREAD

**Issue by 3rdstage** [raydac/mvn-golang#25]
Inside the downloaded the Go SDK, there is x.exe which is reported to be malicious by AVG.
Check and correct it.

**Comment by raydac** [comment]
as I see the file presented in the standard SDK downloaded from the official site, the file presented only in windows versions of 1.9.1 and I can't find similar file in Linux version, [I have written question into the Golang Google group]()https://groups.google.com/d/msg/golang-nuts/b2s88wyGLlg/_6pgUO_NAwAJ

**Comment by raydac** [comment]
[I have created issue in GoSDK project](https://github.com/golang/go/issues/22266)
