### ISSUE TITLE
Unable to build k8s.io dependencies

### ISSUE THREAD

**Issue by gnavgire** [raydac/mvn-golang#26]
We are using maven to build an extension app to kubernetes. We tried adding the k8s.io dependency in our pom.xml but it throws below error

[ERROR] ---------Exec.Err---------
[ERROR] can't load package: package k8s.io/apimachinery: no Go files in /root/../../../src/k8s.io/apimachinery
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

How to add these dependencies.

**Comment by raydac** [comment]
I took some example from client-go and have added it into test examples, take a look pls [https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-kubernetes](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-kubernetes)

**Comment by raydac** [comment]
@gnavgire did it help?
