### ISSUE TITLE
How to resolve dependencies from another folder

### ISSUE THREAD

**Issue by RDevet** [raydac/mvn-golang#4]
For example, if I have the following:
src/hello.go
src/config/config.go
src/utils/utils.go

If config.go depends on utils.go what should the import inside config.go look like so that it finds utils.go?
 I am getting a "cannot find package" error when using absolute imports.

**Comment by raydac** [comment]
and what is the package of config.go?

**Comment by raydac** [comment]
good article about go packages
http://thenewstack.io/understanding-golang-packages/
