### ISSUE TITLE
override $GOPATH

### ISSUE THREAD

**Issue by Vigneshr6** [raydac/mvn-golang#43]
I need to use all the system variables but not $GOPATH and I want to add my source directory to my custom GOPATH as well.

So I did this
```
<useEnvVars>true</useEnvVars>
<env>
       <GOPATH>${basedir}/lib</GOPATH>
</env>
<addToGoPath>
	<mySource>${basedir}</mySource>
</addToGoPath>
```
If I override $GOPATH,then `<addToGoPath>` is not working

**Comment by raydac** [comment]
as I understand you have a project with multiple-source folders, I have added some test example https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-helloworld-multisrc , why you can't use such approach?

**Comment by Vigneshr6** [comment]
@raydac I used the same approach that you shared.
`<addToGoPath>` will append my source folder to system $GOPATH.
But how to override the system $GOPATH with my source folders.

**Comment by raydac** [comment]
if you add custom GOPATH into `env` section then it hides GOPATH formed by the plug-in and in the case you have to make work of plug-in manually, in the case the env section of my example will look like
```
<useEnvVars>true</useEnvVars>
<env>
   <GOPATH>${env.GOPATH}${path.separator}${basedir}${file.separator}lib1${path.separator}${basedir}${file.separator}lib2${path.separator}${basedir}${file.separator}src</GOPATH>
</env>

```

**Comment by Vigneshr6** [comment]
thanks @raydac 
It works
