### ISSUE TITLE
How to set the name of the executable file 

### ISSUE THREAD

**Issue by erandacr** [raydac/mvn-golang#45]
I want to set the name of the executable file, which is getting built. I tried to find the way to do this from pom but couldn't find. Is there a way to do it, if so can you please let me know how.

**Comment by raydac** [comment]
by default the build mojo uses ${project.build.finalName} variable as the result name, it can be redefined through `<finalName>yourname</finalName>` in the build section, also you can provide the name directly in build goal configuration through `<resultName>yourname</resultName>`, ou can take a look at my project https://github.com/raydac/bkbin2wav/blob/master/gobkbin2wav/pom.xml where I use `<resultName>`

**Comment by erandacr** [comment]
Thanks, your example is really helpful.
Will try it out. :)

**Comment by erandacr** [comment]
It worked, thanks
