### ISSUE TITLE
build doesn't fail on test failure

### ISSUE THREAD

**Issue by bogdanpredescu** [raydac/mvn-golang#5]
Seems tests are not sensed by maven build. I suppose that's why Jenkins doesn't see them either.

**Comment by raydac** [comment]
if test is not ok then wrapped process returns not-zero result and the plugin fails process, for instance on my machine I see such picture
```
[INFO] ---------Exec.Out---------
[INFO] --- FAIL: TestHello (0.00s)
[INFO] FAIL
[INFO] FAIL     _/home/igorm/Temp/gohello/gohello/src   0.002s
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.000s
[INFO] Finished at: Tue Jun 07 14:14:22 EEST 2016
[INFO] Final Memory: 9M/238M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.1.0:test (default-test) on project gohello: Process exit code : 1 -> [Help 1]

```

**Comment by bogdanpredescu** [comment]
I am running mvn clean install with mvninstall set as goal for mvn-golang plugin.

INFO] ....Environment vars....
[INFO]  $GOROOT = C:\Program Files (x86)\GO
[INFO]  $GOPATH = X:\workspace\prog\program;X:\workspace\prog\program\src\client
[INFO]  $GOBIN = X:\workspace\prog\program\bin
[INFO]  $PATH = ...C:\Program Files (x86)\GO\bin;X:\workspace\prog\program\bin
[INFO] ........................
[INFO] 
[INFO] ---------Exec.Out---------
[INFO] --- FAIL: TestGET (0.00s)
[INFO] FAIL
[INFO] ok  	client	0.158s
[INFO] 
[ERROR] 
[ERROR] ---------Exec.Err---------
[ERROR]  200
[ERROR] 
[ERROR] Length: 0 []
[ERROR] Status: 200
[ERROR] 
....
INFO] --- mvn-golang-wrapper:2.1.0:mvninstall (default) @ program ---
[INFO] Installing X:\workspace\program\program\bin\program-0.0.1-SNAPSHOT.mvn-golang to C:\...\.m2\repository\myprog\program\0.0.1-SNAPSHOT\program-0.0.1-SNAPSHOT.mvn-golang
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by bogdanpredescu** [comment]
here's how my pom looks like:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
    <parent>
        <groupId>my.group.id</groupId>
        <artifactId>prog</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
  
    <groupId>program</groupId>
    <artifactId>program</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>mvn-golang</packaging>
  
    <properties>
        <basedir>${project.basedir}</basedir>
        <go.sdk.version>1.6</go.sdk.version>
        <mvn-golang-version>2.1.0</mvn-golang-version>
        <source.plugin.version>2.2.1</source.plugin.version>
    </properties>
   
    <build>
        <sourceDirectory>${project.basedir}${file.separator}src${file.separator}client</sourceDirectory>
        <directory>${project.basedir}${file.separator}bin</directory>
        
        
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${source.plugin.version}</version>
                <configuration>
                    <skipSource>true</skipSource>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>com.igormaznitsa</groupId>
                <artifactId>mvn-golang-wrapper</artifactId>
                <version>${mvn-golang-version}</version>
                <extensions>true</extensions>
                <configuration>          
                    <disableSdkDownload>true</disableSdkDownload>
                    <goRoot>${env.GOROOT}</goRoot>
                    <goPath>${project.basedir}</goPath>
                    <goVersion>${go.sdk.version}</goVersion>
                    <verbose>true</verbose>                    
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>mvninstall</goal>
                        </goals>
                        <configuration>
                            <packages>                                
                                <package>client.go</package>
                            </packages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>            
        </plugins>
    </build>

</project>`

**Comment by raydac** [comment]
could you show the body of TestGET? looks very strange, like logging on level of test prints errors but doesn't make fail for test

**Comment by bogdanpredescu** [comment]
there is nothing special about it:

func TestGET(t *testing.T) {
...
if runtimeValue != 0 {
			t.Fail()
		}
...

**Comment by bogdanpredescu** [comment]
Actually you're right and I'm sorry for causing this trouble. In the same function I had another assertion.. very bad practice I know... Thanks and apologies again!

**Comment by bogdanpredescu** [comment]
This issue can be closed as Invalid. Would you happen to know why Jenkins doesn't see the tests though?

**Comment by bogdanpredescu** [comment]
actually I thought it's my previous test's fault as I was testing two things in the same function but this simple example recreates the issue:

func TestFailure(t *testing.T) {
	var client = NewClient()
	if client != nil {
		t.Fail()
	}
}

[....]
[INFO] ........................
[INFO]
[INFO] ---------Exec.Out---------
[INFO] --- FAIL: TestFailure (0.00s)
[INFO] --- FAIL: TestGET (0.00s)
[INFO] FAIL
[INFO] ok       client  0.172s
[INFO]
[ERROR]
[ERROR] ---------Exec.Err---------
[ERROR]  200
[ERROR]
[ERROR] Length: 0 []
[ERROR] Status: 200
[ERROR]
[INFO]
[INFO] --- mvn-golang-wrapper:2.1.0:test (default) @ progname ---
[...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by raydac** [comment]
make please 
`mvn package -X >> log.txt`
and attach the log

**Comment by bogdanpredescu** [comment]
Please find attached.
[log.txt](https://github.com/raydac/mvn-golang/files/302707/log.txt)
[log_clean_install.txt](https://github.com/raydac/mvn-golang/files/302708/log_clean_install.txt)

**Comment by raydac** [comment]
could you change body of the test to just fail, process is still non failed?
```
func TestFailure(t *testing.T) {
    t.Fail()
}
```

**Comment by bogdanpredescu** [comment]
Done, however no difference.

**Comment by raydac** [comment]
and if to test without wrapper with just `go test` then what is the result of the execution? (it can be printed with `echo %ERRORLEVEL%` for last command)

**Comment by bogdanpredescu** [comment]
Here it is:
go test
--- FAIL: TestAlwaysFailing (0.00s)
 200

Length: 0 []
Status: 200

FAIL
ok      client  0.150s

X:\workspace\prog\program\src\client>echo %ERRORLEVEL%
0

**Comment by raydac** [comment]
as you can see and without maven plugin it is OK, or it looks like that `go test` returns false positive result for tests

**Comment by bogdanpredescu** [comment]
That's a good point, many thanks!

It was my main test function containing only

func TestMain(m *testing.M) {
   m.Run()

instead of 

os.Exit(m.Run())

However still, maven does not seem to "sense" the golang tests. In the maven test reports I get 0 tests.

**Comment by bogdanpredescu** [comment]
I suppose the mvn golang plugin needs to write a test report what maven will understand?

**Comment by raydac** [comment]
standard maven plugins know nothing about golang and its test toolchain, they work only with java junit tests and integration tests so that 0 tests is expected
for golang sometime is good to use [GoConvey tool](https://github.com/smartystreets/goconvey)
```
<execution>
  <id>default-get</id>
  <configuration>
    <buildFlags>
      <flag>-u</flag>
    </buildFlags>
    <packages>
      <package>github.com/smartystreets/goconvey</package>
    </packages>
  </configuration>
</execution>
<execution>
  <id>default-test</id>
  <configuration>
    <buildFlags>
      <flag>-v</flag>
    </buildFlags>
  </configuration>
</execution>       
```

**Comment by bogdanpredescu** [comment]
Thanks! However GoConvey doesn't seem to have anything to do with Jenkins.. Closing this issue anyway since the title indicates to something that was clarified.
