### ISSUE TITLE
add dependencies to git

### ISSUE THREAD

**Issue by hleong25** [raydac/mvn-golang#53]
Hello

We have a few dependencies that is part of our project. With these dependencies, we would like to add it with the project so during our build process, so it doesn't need to grab it from github or whatever repo it is every single time. We had issues in the past where it would fail the build because it was not able to grab the dependencies.

If I "git add vendor/", this is the output:

```
warning: adding embedded git repository: project/vendor/src/github.com/akavel/rsrc
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> project/vendor/src/github.com/akavel/rsrc
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached project/vendor/src/github.com/akavel/rsrc
hint:
hint: See "git help submodule" for more information.
```

Can you help?

**Comment by raydac** [comment]
I didn't catch the issue, could you describe in more details? do you use mvn-golang and it generates such content?

**Comment by hleong25** [comment]
We have a project that has multiple dependencies. For each build, the build system will "git clone" the project and run "mvn clean install". As you know, the mvn command will also grab the dependencies (go get xyz). Intermittently the build would fail because it would fail to grab the dependencies. As a fix/workaround, we would fetch the dependencies, remove ".git" directory and add it to our project.

Fast forward to now, I am trying to utilize the mvn-goplugin add dependencies feature. So I am able to use the `mvn.golang.get.packages.file` to define all the dependencies. Now I am trying to add the dependencies (files from the "vendor" directory) to the project, so it doesn't grab them each time the build environment does a build.

**Comment by raydac** [comment]
mvn-golang plugin allows to add any external folder into GOPATH with `<addToGoPath><folder>somefolder</folder></addToGoPath>`, you can create some folder with source of dependencies, for instance `vendor/src` (keep in mind that golang looks fo sources in `src`) where collect dependencies and Go will find them during build

**Comment by hleong25** [comment]
After adding the dependencies, I am able to build fine.
But, I want to add the dependencies to GIT so the build environment doesn't have to pull the dependencies every time.

So after i do a "git add vendor", i get the following warning:
```
warning: adding embedded git repository: project/vendor/src/github.com/akavel/rsrc
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> project/vendor/src/github.com/akavel/rsrc
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached project/vendor/src/github.com/akavel/rsrc
hint:
hint: See "git help submodule" for more information.
```

I don't want to add the dependencies as a git submodule because I believe the build env will need to fetch it from github, which defeats the purpose of adding the `vendor` directory to the repo.

**Comment by raydac** [comment]
as I see git complains for .git folders found in your vendor sub-folder, do you need their git repository info? if not then you can just remove all .git folders in vendor folder and make dependencies as part of your repository

**Comment by hleong25** [comment]
We can close this issue.

It is a user error on my part. Before I would do `git add vendor` to add ALL the dependencies. And that is where I got the issue. If I add each dependency manually `git add vendor/src/dep1`, then i don't have this issue.
