### ISSUE TITLE
correctly process stderr output of golang tools if no errors

### ISSUE THREAD

**Issue by daqingshu** [raydac/mvn-golang#55]
when use go 1.11.x
config GO111MODULE = on
use go.mod file
when mvn compile, the console output like this:

[ERROR] ---------Exec.Err---------
[ERROR] go: finding github.com/modern-go/reflect2 v1.0.1
[ERROR] go: finding github.com/json-iterator/go v1.1.5

I think this just the go common output, not ERROR 
want get help, thanks

**Comment by raydac** [comment]
unfortunately I can do nothing in the case because everything works correct
I don't know why but Golang team exactly uses err stream to print such messages
```
if !QuietLookup {
			fmt.Fprintf(os.Stderr, "go: finding %s %s\n", r.path, rev)
		}
``` 
and my wrapper just shows what it gets from error stream

**Comment by raydac** [comment]
I have created [issue report for golang team](https://github.com/golang/go/issues/29848)

**Comment by raydac** [comment]
I will make some improvements in plugin to log their messages because looks like that they just use error stream to log auxiliary info
