### ISSUE TITLE
`go get` from artfactory

### ISSUE THREAD

**Issue by sunnylbk** [raydac/mvn-golang#56]
Thanks a lot for this plugin.

Many of the artifacts that we use are internal packages which reside in artifactory. Is there a way to configure `go get` to use artifactory so that packages can also be downloaded from there?

Thanks

**Comment by raydac** [comment]
I didn't catch what do you mean? as I know `go get` just takes link to package and load it, for instance `bitbucket.org/raydac/mvn-plugin-cvs-hg-test` will load package from __bitbucket.org__ and `github.com/raydac/mvn-golang-cvs-test` from __github.com__, you can place your package in any place with CVS supported by  golang (it supports HG, GIT, SVN, BAZAAR)

**Comment by raydac** [comment]
ok, I will investigate the approach

**Comment by sunnylbk** [comment]
Thanks

**Comment by raydac** [comment]
I have added way to make calls to JFrog CLI tool with tuned GoSDK environment
you can take a look at [example](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-jfrog-cli)
the tool works with go.mod so that my default-get should not be used in the case as I see

**Comment by raydac** [comment]
golang wrapper usually work with its own tuned environment and paths, if you have already tuned system  variables for Golang and want use them then you can enable their reexport with `<useEnvVars>true</useEnvVars>` or you can add any needed path directly into GOPATH list with `<addToGoPath><path>some/path/to/folder</path></addToGoPath>`

**Comment by sunnylbk** [comment]
I did run with `<useEnvVars>true</useEnvVars>` to keep maven environment similar to as running from terminal.

This is the configuration I am working with 

```
    <build>
        <sourceDirectory>${basedir}${file.separator}src</sourceDirectory>
        <directory>${basedir}${file.separator}bin</directory>
        <plugins>
            <plugin>
                <groupId>com.igormaznitsa</groupId>
                <artifactId>mvn-golang-wrapper</artifactId>
                <version>2.2.1-SNAPSHOT</version>
                <extensions>true</extensions>
                <configuration>
                    <useEnvVars>true</useEnvVars>
                    <goVersion>1.11.4</goVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>call-jfrog-cli</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>jfrog-cli</goal>
                        </goals>
                        <configuration>
                            <cliPath>${jfrogcli.path}</cliPath>
                            <target>rt</target>
                            <command>go</command>
                            <arguments>
                                <arg>build</arg>
                                <arg>go</arg>
                                <arg>--url={change-me}</arg>
                                <arg>--user={change-me}</arg>
                                <arg>--password={change-me}</arg>
                                <arg>--build-name=my-build</arg>
                                <arg>--build-number=1</arg>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by raydac** [comment]
try to add in common config `<env><GO111MODULE>on</GO111MODULE></env>`

**Comment by sunnylbk** [comment]
Ah, that did the trick. Thank you so much!!

**Comment by raydac** [comment]
great, keep me informed about issues with project build

**Comment by sunnylbk** [comment]
So, I have been using the plugin to retrieve from artifactory. It's working well locally. I was also able to get this working drone CI with the configuration below:

```
pipeline:
  build:
    image: maven
    commands:
      # Essential packages
      - apt-get update
      - apt-get install build-essential -y
      - export M2_HOME=/usr/share/maven
      - mvn clean deploy --settings .travis.settings.xml
```

where `.travis.settings.xml` has configuration related to artifactory.

Recently, we switched to Travis CI and using a similar config is resulting in errors while trying to retrieve go libraries. This is the configuration used for Travis

```
language: java
sudo: true
install: true
script:
  # Essential packages
  - sudo apt-get update
  - sudo apt-get install build-essential -y
  - export M2_HOME=/usr/local/maven
  - mvn clean deploy --settings .travis.settings.xml
```

It's resulting in errors like below

```
[INFO] --- mvn-golang-wrapper:2.2.1-SNAPSHOT:jfrog-cli (call-jfrog-cli) @ <repo> ---
[INFO] JFrog CLI: /home/travis/build/<team>/<repo>/../jfrogcli/jfrog-linux
[INFO]    Target: rt
[INFO]   Command: go
[INFO] 
[INFO] ---------Exec.Out---------
[INFO] main.go:10:2: cannot find package "github.com/aws/aws-lambda-go/lambda" in any of:
[INFO] 	/home/travis/.mvnGoLang/go1.11.4.linux-amd64/src/github.com/aws/aws-lambda-go/lambda (from $GOROOT)
[INFO] 	/home/travis/.mvnGoLang/.go_path/src/github.com/aws/aws-lambda-go/lambda (from $GOPATH)
[INFO] 	/home/travis/build/<team>/<repo>/src/github.com/aws/aws-lambda-go/lambda
```

The same configuration works locally too. 

Is there any gotcha for Travis? Please let me you know if you have an insight into this.

Thanks in advance.

**Comment by sunnylbk** [comment]
Ok, I was able to get around the issue by using go base image 

```
language: go
sudo: false
install: true
script:
  - export M2_HOME=/usr/local/maven
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mvn -U clean deploy --settings .travis.settings.xml;
    fi
```

**Comment by sunnylbk** [comment]
Have another question, can the `install` phase of the plugin be configured to generate an artifact that could be used as a go dependency in another repo?
Thanks

**Comment by raydac** [comment]
as I see there was some problem with rights in travis, I didn't test plugin with travis so that if you find errors or ways to improve to work with the CI, I can make changes in plugin

during install my plugin just zip whole project sources and resources and save it into maven repository as archive with mvn-golang extension, it can't be used as a standard Go dependency because Go knows nothing about maven but I guess it is possible to load and unpack sources from the artifact through  standard maven plugins like [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/) and even build them as another maven process through [maven-invoker-plugin](https://maven.apache.org/plugins/maven-invoker-plugin/index.html)

**Comment by raydac** [comment]
I have checked approach with maven dependency plugin and [it looks working](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-maven-repository), but I had to change resulted installed  artifact extension to `zip` because the dependency plugin processes extension and it know nothing about `mvn-golang` type

**Comment by sunnylbk** [comment]
Thanks for the above idea.
I riffed off your code and am able to automatically rename `.golang` to a `.zip`. Working example [here](https://github.com/sunnylbk/mvn-golang-lib-example). Am unpacking into `GOPATH` folder so that it's visible globally.

But with this change, I am having an issue. The new build is unable to replace the old file.
```
[INFO] --- mvn-golang-wrapper:2.2.1-SNAPSHOT:get (default-get) @ mvn-golang-lib ---
[WARNING] Value GOPATH is replaced by environment value.
[INFO] Prepared command line : bin/go get ./...
[ERROR]
[ERROR] ---------Exec.Err---------
[ERROR] go get: no install location for /Users/bharath/Work/Open-source/mvn-golang-lib-example/mvn-golang-lib/src/com/sunnylbk/mvngotest: hidden by /Users/bharath/.go/src/com/sunnylbk/mvngotest
[ERROR]
```

When I manually delete the file from there, next build works fine. I see `overwrite` flag is set to true. Any idea why this is happening?

**Comment by raydac** [comment]
I have added auto-search of artifacts generated by mvn-golang plugin in dependencies, unpack them into folder, and adding them automatically into GOPATH, so it started work like regular maven projects

**Comment by sunnylbk** [comment]
Thanks!

I tried to add mod files into existing maven repository examples, but encountering the following error

```
[INFO] Prepared command line : bin/go get ./...
[ERROR]
[ERROR] ---------Exec.Err---------
[ERROR] go build com/igormaznitsa/mvngotestmeta: no Go files in
[ERROR]
```

It did work before adding mod files.
Any thoughts on this?

**Comment by raydac** [comment]
it looks like that such error for turned on GO11MODULE during build, I will investigate

**Comment by raydac** [comment]
```
If GO111MODULE=on, then the go command requires the use of modules,
never consulting GOPATH. We refer to this as the command being
module-aware or running in "module-aware mode".
```
mvn-golang mainly work through GOPATH variable and downloaded and unpacked dependencies from maven repository are added into GOPATH but GO11MODULE=on is turn off GOPATH mechanism and it breaks work as I see
