### ISSUE TITLE
mvn-golang:vet  does not have maven dependency resolution

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#59]
My build with mvn-golang:vet fails due to lack of  GOPATH setup 

I believe 'vet' goal  should shave the same maven dependency resolution of the 'build' goal: requiresDependencyResolution = ResolutionScope.COMPILE

**Comment by raydac** [comment]
could you describe situation more detailed? step by step to reproduce

**Comment by dantran** [comment]
sorry about the confusion,  i have multi maven modules with Go and I would like to run mvn-golang:vet
In this example 2 should be sufficient

    common
    main

main depends on maven via mvn-golang maven dependency

Normal   'build' gold works, since man can reference 'common'  since the GOPATH is set correctly ( ends with target/__dep__/common-x.y.x)

'vet' goal fail to find  'common'  since GOPATH does not have 'common' in its path

**Comment by raydac** [comment]
good point, I will add a test for such case and fix

**Comment by dantran** [comment]
will you deploy a snapshot to sonatype snapshot repo?love to test it right away

**Comment by dantran** [comment]
the fix looks good, I am able to see Go Vet result. Many thanks.

**Comment by raydac** [comment]
I will add test for other go commands and if all is ok then release new version

**Comment by raydac** [comment]
I have published 2.3.2 version with the fix in maven central
