### ISSUE TITLE
mvninstall doesn't seem to work

### ISSUE THREAD

**Issue by bogdanpredescu** [raydac/mvn-golang#6]
I am using mvninstall as a goal and the resulted binary (named as the artifact, without .exe) doesn't get copied into local mvn repo. Please advise.

**Comment by raydac** [comment]
mvninstall doesn't install result of build, it packs all sources and resources and places into maven repository as zip file, it would be very strange to install result because it can be very different, but if you need that then just use such code snippet and add it into build section
```
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
          <executions>
            <execution>
              <id>save-result-as-artifact</id>
              <phase>install</phase>
              <goals>
                <goal>install-file</goal>
              </goals>
              <configuration>
                <file>${basedir}${file.separator}bin${file.separator}${project.build.finalName}</file>
                <groupId>${project.groupId}</groupId>
                <artifactId>${project.artifactId}-result</artifactId>
                <version>${project.version}</version>
               <!-- NB! packaging allows to select extension  -->
               <packaging>bin</packaging>
              </configuration>
            </execution>
          </executions>
	</plugin>
```

**Comment by bogdanpredescu** [comment]
Thanks. I fail to see though why it's strange to install the result since that is the actual artifact..
When building java projects jar files are result files which get put into the maven repository while sources are optional.

**Comment by raydac** [comment]
you can build many executable files for different platforms and how in the case to select which result to include as result artifact? and also it will be very strange to have artifacts for different platforms provided under the same identifier in maven repository

**Comment by bogdanpredescu** [comment]
It wouldn't bother me having the project binaries copied under .m2\repository\progam\program-version\ 
If I further want to create an assembly (pack them in a zip) that could be even nicer although should be optional.

**Comment by raydac** [comment]
maven is very powerful tool and allows to make any usage, just disable default mvninstall  
```
 <execution>
            <id>default-mvninstall</id>
            <phase>none</phase>
</execution>
```
and use the `install-file` code snippet  to install needed executable artifact

**Comment by bogdanpredescu** [comment]
Thanks, since there is a way around this I guess this issue can be closed.
