### ISSUE TITLE
Add ability for maven plugin to obtain GOROOT location 

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#61]
my maven project set the required GO version where mvn-golang automatically download and place GO sdk under ~/.mvngolang

Requesting mvn-golang to push the download GOROOT path to a maven property ( like ${go.root} so I can retrieve it for other purposes

For my case, I need to run another external script  which needs the location of my GOROOT (https://github.com/kubernetes/code-generator/blob/master/generate-groups.sh)

if user passes in <goRoot> plugin parameter, mvn-golang should push it into the property  as well

**Comment by raydac** [comment]
am I correct that you want just get path to downloaded go sdk? maven is declarative one and there is not guarantee that property will be presented in time, if you want path to sdk and paths not changed then it can be just `<go.sdk.path>${user.home}/.mvnGoLang/go1.12.4.linux-amd64</go.sdk.path>`

**Comment by dantran** [comment]
no perfer to let sdk and path changes per platform and version, since user can use it too

I think it is possible to introduce a mvn-golang's goal running at validate phase  pushing the sdk download dir to a maven property, this way subsequence phases can obtain the prop

**Comment by raydac** [comment]
now I am setting project parameter `mvn.golang.goroot.last` by the last used goroot value

**Comment by dantran** [comment]
looks i can also play tricks with mvn profiles. 

    <profile>
      <id>linux</id>
      <activation>
        <os>
          <family>Linux</family>
        </os>
      </activation>
      <properties>
        <go.root>${env.HOME}/.mvnGoLang/go${go.version}.linux-amd64</go.root>
      </properties>
    </profile>
    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <properties>
        <go.root>${env.USERPROFILE}/.mvnGoLang/go${go.version}.windows-amd64</go.root>
      </properties>
    </profile>

**Comment by raydac** [comment]
yes, it also a way, so I will rollback my changes

**Comment by dantran** [comment]
found out the profile trick is very convoluted, much better to use the prop from mvn-golang

**Comment by raydac** [comment]
so after execution there are project properties
- `mvn.golang.last.goroot`
- `mvn.golang.last.gopath`
-`mvn.golang.last.gobin`
-`mvn.golang.last.gocache`
-`mvn.golang.last.go386`
-`mvn.golang.last.goos`
-`mvn.golang.last.goarm`
-`mvn.golang.last.goarch`
-`mvn.golang.last.goroot_bootstrap`
-`mvn.golang.last.path`

**Comment by dantran** [comment]
is there such a goal to download Go SKD if not available yet and populate the above properties

This is for dev env setup use case

   * Run that goal to download SDK
   * Run an external setup script that required step1 properties as its env

This is for dev who prefer to run Go command directly but need env used by mvn-golang

**Comment by raydac** [comment]
there is `custom` mojo, try call a command which does nothing like
```
<execution>
   <id>get-go-version</id>
   <phase>validate</phase>
   <goals>
       <goal>custom</goal>
   </goals>
   <configuration>
      <customCommand>version</customCommand>
   </configuration>
</execution>
```

**Comment by dantran** [comment]
it works.  Thanks

**Comment by dantran** [comment]
Could you release 2.3.3 for this feature?
