### ISSUE TITLE
threadsafe mvn-golang

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#63]
My maven multithread build shows this warning

    [WARNING] The following plugins are not marked @threadSafe in kubernetes-controller:
    [WARNING] com.igormaznitsa:mvn-golang-wrapper:2.3.3-SNAPSHOT

not sure if this plugin is threadsafe, so far it working great for me

if so, please mark it threadsafe where possible

**Comment by raydac** [comment]
I made some refactoring and now it should support parallel work, I just lock maven session during work of mvn golang mojo which need work sequentially

**Comment by dantran** [comment]
confirmed, I no longer see the warning. Thank you
