### ISSUE TITLE
example to build all thirdparty as a share lib ( .so)

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#64]
I have a legal requirement to build all thirdparty modules into one .so file,  the project Go fiels become an executable. Possible?

**Comment by raydac** [comment]
if you mean build of golang plug-ins (which also .so files) then you can take a look at [the example](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-plugin)

**Comment by dantran** [comment]
dont think it is what i am lookgin for. 

I am looking for one maven golang module which produces one executable and one .so files which bundle all  thirdparty found under go.mod

By default, Go build creates one single executable

**Comment by dantran** [comment]
perhaps we can get mvn-golang to generate a vendor content, then I can run Go build with -buildmode=shared against 'vendor' directory
