### ISSUE TITLE
Is there a way to skip the fmt/fix modules?

### ISSUE THREAD

**Issue by MarcFraioli** [raydac/mvn-golang#65]
I don't want the build to reformat my code, is there a way to disable the use of `go fmt` and `go fix`? Thanks.

**Comment by raydac** [comment]
they are active in `default` so that try please add pair execution descriptors
```xml
<executions>
  <execution>
    <id>default-fix</id>
    <phase>none</phase>
  </execution>
  <execution>
    <id>default-fmt</id>
    <phase>none</phase>
  </execution>
</executions>
```

**Comment by raydac** [comment]
I think it is a good idea to provide properties to skip such steps

**Comment by MarcFraioli** [comment]
Thanks Igor, putting it in phase "none" worked perfectly. I'll try the new properties as well if they're available.

**Comment by raydac** [comment]
it is provided in release 2.3.3
