### ISSUE TITLE
go get is not not downloading required packages

### ISSUE THREAD

**Issue by sriram275** [raydac/mvn-golang#67]
go get is not not downloading required packages which are added like below

```
module github.com/sirupsen/logrus

require (
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/konsorten/go-windows-terminal-sequences v1.0.1
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/stretchr/objx v0.1.1 // indirect
	github.com/stretchr/testify v1.2.2
	golang.org/x/sys v0.0.0-20190422165155-953cdadca894
)
```

when po.xml is like below
```
<execution>
            <id>default-get</id>
            <configuration>
              <packages>
                <package>github.com/Sirupsen/logrus</package>
              </packages>
            </configuration>
          </execution>
```

**Comment by raydac** [comment]
I have made some [test-example](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-logrus) with similar pom and added into example list, I don't see any errors during build. It would be good if you would provide build log text

**Comment by sriram275** [comment]
May be some issue with my setup. So i am adding all dependent packages in pom.xml. Hence closing this.

Thanks
