### ISSUE TITLE
ldflags -X not working when building under linux/macos

### ISSUE THREAD

**Issue by mgaudig72** [raydac/mvn-golang#68]
Hi,
we have a project that uses the ldflags -X option to inject the project version as a variable into the build:
```
                        <configuration>
                            <targetOs>linux</targetOs>
                            <targetArch>amd64</targetArch>
                            <resultName>sample-linux-amd64</resultName>
                            <env>
                                <CGO_ENABLED>0</CGO_ENABLED>
                            </env>
                            <buildFlags>-a</buildFlags>
                            <ldFlags>"-X main.ProjectVersion=${project.version}"</ldFlags>
                            <packages>
                                <app>main.go</app>
                            </packages>
                        </configuration>
```
```
package main

import (
	"fmt"
)

var ( // Build time injected vars
	ProjectVersion = "XXXX.XX.X"
)

func main() {

	fmt.Println(fmt.Sprintf("Project-Version %s", ProjectVersion))
}
```

When you run maven under windows, the project value is injected correctly. All created binarys contain the value and print "Project-Version 1.0.0-SNAPSHOT".

But if you run maven under linux or macos, the version is not injected (without any error or warning) and "Project-Version XXXX.XX.X" is printed to stdout.

Any idea why this occurs? 

Here is a sample project attached, which can be used to reproduce the problem.
[sample.zip](https://github.com/raydac/mvn-golang/files/3569232/sample.zip)

BTW, great plugin.

Cheers,
   Malte

**Comment by raydac** [comment]
it looks like that you are not correct in use of configuration flags, if you see any XXXflags in configuration, keep in mind that it means list of strings, so that your configuration should be
```xml
<buildFlags>
   <flag>-a</flag>
</buildFlags>
<ldFlags>
   <flag>-X</flag>
   <flag>main.ProjectVersion=${project.version}</flag>
</ldFlags>
```

**Comment by mgaudig72** [comment]
Sorry, you're absoluty right. That did the trick. Thanks, mate!

**Comment by raydac** [comment]
I made some [mind map contains examples of parameter use](https://raw.githubusercontent.com/raydac/mvn-golang/master/assets/doc_common.png)
