### ISSUE TITLE
Is it possible to bundle some build info with final build?

### ISSUE THREAD

**Issue by sriram275** [raydac/mvn-golang#69]
I want to print the build info when some one is starting by clicking this binary. Is there a way to achieve this?

Thanks,
Sriram

**Comment by raydac** [comment]
you can generate build label with [build number maven plugin](https://www.mojohaus.org/buildnumber-maven-plugin/usage.html) and provide the number you can through build flags like
```xml
<ldFlags>
     <flag>-X</flag>
     <flag>"main.Buildstamp=${buildNumber}"</flag>
</ldFlags>
``` 
but in the case you have to have variable in main
```go
var Buildstamp string
```
I use such trick in my [hello world test](https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-helloworld) but I use more complex approach with linux script call to get date

**Comment by raydac** [comment]
did the info help?

**Comment by sriram275** [comment]
Added same as suggested like below

```
<configuration>
    <resultName>gobuild.sh</resultName>
    <targetOs>linux</targetOs>
    <targetArch>amd64</targetArch>
    <ldFlags>
        <flag>-X</flag>
        <flag>"main.Buildstamp=${goBuildNumber}"</flag>
    </ldFlags>
</configuration>
```

But getting following error 

Scanning maven dependencies
[INFO] Prepared command line : bin\go.exe build -buildmode=default -ldflags -X "main.Buildstamp=2019-09-15 21:11:37.800" -o F:\Code\target\gobuild.sh
[ERROR]
[ERROR] ---------Exec.Err---------
[ERROR] can't load package: package 21:11:37.800: cannot find package "21:11:37.800" in any of:
[ERROR]         C:\Users\xxxx\.mvnGoLang\go1.12.9.windows-amd64\src\21:11:37.800 (from $GOROOT)
[ERROR]         C:\Users\xxxx\.mvnGoLang\.go_path\src\21:11:37.800 (from $GOPATH)
[ERROR]         F:\Code\src\21:11:37.800
[ERROR] can't load package: package -o: cannot find package "-o" in any of:


Am I missing something?

Thanks.

**Comment by raydac** [comment]
I am trying such pom.xml and can't reproduce the error
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.igormaznitsa</groupId>
  <artifactId>mvn-golang-example-hello-world</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>mvn-golang</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <mvn.golang.go.version>1.13</mvn.golang.go.version>
    <goBuildNumber>2019-09-15 21:11:37.800</goBuildNumber>
  </properties>

  <build>
    <sourceDirectory>${basedir}${file.separator}src</sourceDirectory>
    <directory>${basedir}${file.separator}bin</directory>
    <plugins>
      <plugin>
        <groupId>com.igormaznitsa</groupId>
        <artifactId>mvn-golang-wrapper</artifactId>
        <version>2.3.3</version>
        <extensions>true</extensions>
        <executions>
      	  <execution>
   		<id>default-build</id>
      		<configuration>
                    <resultName>gobuild.sh</resultName>
                    <targetOs>linux</targetOs>
                     <targetArch>amd64</targetArch>
                     <ldFlags>
                         <flag>-X</flag>
                         <flag>"main.Buildstamp=${goBuildNumber}"</flag>
                     </ldFlags>
                 </configuration>
    	    </execution>
      	</executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by raydac** [comment]
am I correct that you trying to build linux file under windows?

**Comment by sriram275** [comment]
Yes. It is working fine before adding ldFlags and after adding I am getting the above error.

**Comment by raydac** [comment]
it looks like that under windows, space in goBuildNumber breaks work, try value without spaces

**Comment by sriram275** [comment]
Worked without spaces.

Thakyou so much.

**Comment by sriram275** [comment]
Just saw in [stackoverflow ](https://stackoverflow.com/a/32468331)


Looks like need to enclose the entire argument in quotes.

just sharing... if it helps then great. :)
