### ISSUE TITLE
Speedup Golang download using internal cache

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#71]
At work, we have artifactory to cache google Golang download site.  Is there a way for me to configure mvngolang to use my artifactory instead?

**Comment by raydac** [comment]
it is possible to replace default Golang download site by custom one through _sdkSite_
```
<sdkSite>https://storage.googleapis.com/golang/</sdkSite
```

for direct SDK archive URL there is configuration parameter_ sdkDownloadUrl_
```
<sdkDownloadUrl>https://dl.google.com/go/go1.13.darwin-amd64.tar.gz</sdkDownloadUrl>
```

**Comment by dantran** [comment]
looks like it not possible to replace sdkSite, here is my error

Caused by: java.io.IOException: Can't load list of SDKs from https://my.artifactory.com/webproxy?prefix=go1.13.5.windows-amd64 : 406 Not Acceptable

sdkDownloadUrl is promising.  I can play with Maven profiles per platform

**Comment by dantran** [comment]
confirm sdkDownloadUrl  works 

    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>windows</family>
        </os>
      </activation>
      <properties>
        <go.sdk.url>${go.sdk.site}/go${go.version}.windows-amd64.zip</go.sdk.url>
      </properties>
    </profile>
    <profile>
      <id>linux</id>
      <activation>
        <os>
          <family>linux</family>
        </os>
      </activation>
      <properties>
        <go.sdk.url>${go.sdk.site}/go${go.version}.linux-amd64.tar.gz</go.sdk.url>
      </properties>
    </profile>
    <profile>
      <id>mac</id>
      <activation>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <properties>
        <go.sdk.url>${go.sdk.site}/go${go.version}.darwin-amd64.tar.gz</go.sdk.url>
      </properties>
    </profile>

**Comment by raydac** [comment]
__sdkSite__ should return list of SDK items like original google site
```
<ListBucketResult>
<Name>golang</Name>
<Prefix/>
<Marker/>
<NextMarker>go1.11.8.windows-amd64.msi</NextMarker>
<IsTruncated>true</IsTruncated>
<Contents>
<Key>getgo/installer.exe</Key>
<Generation>1501264926677062</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2017-07-28T18:02:06.630Z</LastModified>
<ETag>"919c6c41be11fbf8a27405e42d033d18"</ETag>
<Size>5131776</Size>
</Contents>
<Contents>
<Key>getgo/installer_darwin</Key>
<Generation>1501264926674843</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2017-07-28T18:02:06.610Z</LastModified>
<ETag>"923241b8b23403d5d5c762afadc9844a"</ETag>
<Size>5157928</Size>
</Contents>
<Contents>
<Key>getgo/installer_linux</Key>
<Generation>1501264926685855</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2017-07-28T18:02:06.632Z</LastModified>
<ETag>"a38297226e0736950f9ee7b96f76ce81"</ETag>
<Size>5179246</Size>
</Contents>
</ListBucketResult>
```
you could try just make xml file with your links and provide its address through sdkSite

**Comment by dantran** [comment]
unfortunately, my artifact does not return the expected content. It just show dir list. 

However, provide a xml file a very good option too

**Comment by dantran** [comment]
false alarm, for some reason, i run into this issue

    [ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.3.4:get (default-get) on 
    project search-monitor: Parsed x-goog-hash has not needed data: 
    XGoogHashHeader(valid=true,md5=null,crc32c=null) -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal 
    com.igormaznitsa:mvn-golang-wrapper:2.3.4:get (default-get) on project search-monitor: Parsed x- 
   goog-hash has not needed data: XGoogHashHeader(valid=true,md5=null,crc32c=null)
 
Any suggestion is greatly appreciated

**Comment by raydac** [comment]
drop stacktrace, in case of maven, you can get stacktrace with `-X` option

**Comment by dantran** [comment]
I only provide full URL to sdkDownloadUrl,   ended up to set  <checkSdkHash>false</checkSdkHash>

**Comment by raydac** [comment]
do you mean that you added
```
<checkSdkHash>false</checkSdkHash>
```
and anyway has the error?

**Comment by raydac** [comment]
@dantran  any news?
