### ISSUE TITLE
Windows build(.exe) Application details

### ISSUE THREAD

**Issue by sriram275** [raydac/mvn-golang#72]
Is possible to configure application details tab fields with any configuration for windows build.?

Like below properties: Product name, version and Copyright:

![image](https://user-images.githubusercontent.com/7270651/78339833-bf293a00-75b2-11ea-850d-06fb3effb51c.png)

Thanks.

**Comment by raydac** [comment]
there is some [golang project](https://github.com/josephspurrier/goversioninfo)
