### ISSUE TITLE
go.mod Backup file is restored in wrong directory

### ISSUE THREAD

**Issue by Theoderich** [raydac/mvn-golang#73]
When the plugin modifies a go.mod file in a build step with moduleMode on, the original go.mod file is copied to ".#go.mod.mvn.orig".
After the build step, the modified go.mod file is replaced with the backed up version.
Unfortunately, the backup restore process is buggy. The backup is always copied to ${project.build.sourceDirectory}/go.mod, regardless to where the original go.mod file that was originally backed up resided. 

For Example:
Before build step:
src/main/go/my-package/go.mod
After build step:
src/main/go/my-package/go.mod <-- file as modified by the plugin
src/main/go/go.mod <-- original go.mod file

This breaks the build, since follow-up build steps now see two go.mod and thus assume that src/main/go is the correct working directory instead of src/main/go/my-package

I have already prepared a simple fix that I will pull request shortly

**Comment by raydac** [comment]
ok, thank you
as I see, the problem in com.igormaznitsa.mvngolang.AbstractGoDependencyAwareMojo#restoreGoModFromBackupAndRemoveBackup
