### ISSUE TITLE
Test -run

### ISSUE THREAD

**Issue by GregDomjan** [raydac/mvn-golang#75]
Confused and still learning about golang

Was sourcing the tests to execute from java system vars rather than maven config or maven properties intentional?

https://github.com/raydac/mvn-golang/blob/cdd76b105182e003fdade85328be5eedc83d0a2a/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/GolangTestMojo.java#L67

to workaround 
```
		<buildFlags>
			<flag>-v</flag>
			<flag>-run</flag>
			<flag>TestNames</flag>
		</buildFlags>
```

**Comment by raydac** [comment]
not very understand what do you mean? golang wrapper plugin has been developed maximally close support standard maven test plugin properties so that I have added way to define test through `test` property and through `package#test`
