### ISSUE TITLE
mvn-golang-wrapper Path Management 

### ISSUE THREAD

**Issue by GregDomjan** [raydac/mvn-golang#76]
Any suggestions on how to join these things together?

Using maven plugin to manage helm
```
<plugin>
	<groupId>com.kiwigrid</groupId>
	<artifactId>helm-maven-plugin</artifactId>
```
It puts the helm executable in `${project.build.directory}/helm`

Using a golang library `github.com/gruntwork-io/terratest/modules/helm`  that requires helm be found 'in the path'

Tried to configure working directory for tests so helm would be in the default folder path

```
<workingDir>${project.build.directory}/helm</workingDir>
```
Not clear on why it didn't work, but helm couldn't be found

Tried to configure the go environment for executing tests to include the helm folder in path
```
			<env>
				<PATH>${project.build.directory}/helm;${env.Path}</PATH>
			</env>
```
Path didn't get set

Found that env for path cannot be configured, due to specific process for path and removing system go 
https://github.com/raydac/mvn-golang/blob/a1dd6d80a54bb3cf8a92a2f20bbd0e769b4498f6/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/AbstractGolangMojo.java#L1819

**Comment by raydac** [comment]
if you want add path then you can use `addToGoPath`
```
<addToGoPath>
     <dir>${helm.path}</dir>
</addToGoPath>
```
