### ISSUE TITLE
Windows OS/module mode: Can't extract module info from tokens

### ISSUE THREAD

**Issue by fmazoyer** [raydac/mvn-golang#80]
On Windows OS, I am getting the following error:

```bash
   Can't extract module info from tokens: [a/b/c, =>, .., .., .., .., ..,module1-directory-1.0.0, src, a, b, c] `
```

Problem can easily be reproduced by slightly modifying JUnit: [GoModTest.java:testComplex4](https://github.com/raydac/mvn-golang/blob/4d0b51ec67c8039ec42d0ce767b5620b0fab20fe/mvn-golang-wrapper/src/test/java/com/igormaznitsa/mvngolang/utils/GoModTest.java#L126), replacing `../goodbye` with `..\goodbye`.

1. **module2** depends on **module1**:
**module2**'s go.mod in `bin\.__deps__\module2-directory-1.0.0\src\d\e\f` looks like:

```bash
module d/e/f
require a/b/c v1.0.0
replace a/b/c => ..\..\..\..\..\module1-directory-1.0.0\src\a\b\c
go 1.15
```
2. __Question__: Is this ok to have **backslashes** here, even though we are on Windows OS?

If not, it looks like backslash character is not taken as a token separator?:

If you would agree that there is a problem, indeed, I tested a simple modification in [TOKENIZER](https://github.com/raydac/mvn-golang/blob/4d0b51ec67c8039ec42d0ce767b5620b0fab20fe/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/utils/GoMod.java#L33), by adding backslash as a separator, and my build is working again.
I can push it for review.

If not, I will let it up to you :-) 

Thanks a lot for this great tool!

Kind regards.

**Comment by raydac** [comment]
Hi
thanks for info, good point
if you have fix for the issue, you could make pull-request
