### ISSUE TITLE
Abiblity to default-build to attach its output executable binary to maven session

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#82]
I have maven go build with has many maven modules, each module produce a go executable

Below the dependecyManagement where I disabel mvn-golang lifecycle and only enable default-build

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.igormaznitsa</groupId>
          <artifactId>mvn-golang-wrapper</artifactId>
          <executions>
            
            
            <execution>
              <id>default-generate</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-fix</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-fmt</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-test</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-mvninstall</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-install</id>
              <phase>none</phase>
            </execution>
            <execution>
              <id>default-build</id>
              <configuration>
                <strip>${go.strip}</strip>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>

I'd like to have the ability to add an additional setting at default-build configure to attach is build output to maven session. 

I currently use maven-antrun-plugin to repeat  each child module, like this

    <plugins>

      <plugin>
        <groupId>com.igormaznitsa</groupId>
        <artifactId>mvn-golang-wrapper</artifactId>
        <extensions>true</extensions>
        <configuration>
          <workingDir>${golang.src.dir}/${project.artifactId}</workingDir> 
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-artifacts</id>
            <phase>package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <attachartifact file="${project.build.directory}/${project.build.finalName}" type="${exe.ext}" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>

Propose settings  for build mojo

    <attached>true</attache>
    <type>xxxx</type>
    <classifier>optional</optional>

**Comment by raydac** [comment]
there is `verbose` flag for all goals and if you make it true then it will print output into log `<verbose>true</verbose>`, also you can turn on it through maven property `mvn.golang.verbose`
```xml
<mvn.golang.verbose>true</mvn.golang.verbose>
```

**Comment by dantran** [comment]
@raydac  i am not sure about verbose flag anything to do with my request having mvn-golang wrapper to attach the output binary to maven session for install/deploy purpose

**Comment by raydac** [comment]
looks like I didn't understand phrase `build output`, if you mean the result binary file generated during build process then there is special parameter `<resultName>` which by default uses maven property `${project.build.finalName}` so that you can use the property to get name of built result file in the build folder

**Comment by raydac** [comment]
yes, looks like that I not correctly understood `build output`
and why do you use ANT task instead of `Maven deploy plugin`? [it allows to deploy generated file with required parameters](https://maven.apache.org/plugins/maven-deploy-plugin/usage.html) into maven repository and use it

**Comment by dantran** [comment]
using ant:attachartifact is correct, it attaches the build artifact Maven so that my go binary will be install and deploy 

what I asking is to update  https://github.com/raydac/mvn-golang/blob/master/mvn-golang-wrapper/src/main/java/com/igormaznitsa/mvngolang/GolangBuildMojo.java

then   attach  ${project.build.directory}/${project.build.finalName} to maven session for the same purpose

**Comment by raydac** [comment]
from point of view of maven of course sounds a bit strange to include platform-depended artifact into resulted artifact but idea is good, I thin it is no so good to provide such functionality by default but I will add special flag and property into mvn-golang build command to attach result artifact (if it found after successful; execution) into maven session artifacts, ok?

**Comment by raydac** [comment]
I have added functionality into `build` mojo, now there are three more properties
- `attach` - boolean (by default false) which allows turn on attach for built result file (or through property `mvn.golang.build.attach`)
- `attachType` - string (by default `bin`) which allows define type for attached artifact (or through property `mvn.golang.build.attach.type`)
- `attachClassifier` - string (by default none) which allows define classifier for attached artifact (or through property `mvn.golang.build.attach.classifier`)

**Comment by dantran** [comment]
@raydac awesome

**Comment by raydac** [comment]
check snapshot pls and if all is ok then pls close the issue

**Comment by dantran** [comment]
it works. this saves a bunch of repeated antrun plugin block. Thanks

**Comment by rbsrafa** [comment]
Hello, I've been testing with this plugin and so far it's amazing.
Regarding this chat, I could get the binary into the generated maven folder, but I'd like to generate it without an extension.
E.g. instead of my-bin.bin -> just my-bin.
I tried to provide a blank `attachType` but I could see in the src code that it defaults to "bin" if not is provided. Would it be possible to leave the default as an empty string and then provided the desired extension if needed? Thanks

**Comment by raydac** [comment]
@rbsrafa 
`attachType` is for artifact installation, could you drop example of your pom?
