### ISSUE TITLE
empty go vet log

### ISSUE THREAD

**Issue by dantran** [raydac/mvn-golang#83]
here is my go vet execution

              <execution>
                <id>go-vet</id>
                <phase>test-compile</phase>
                <goals>
                  <goal>vet</goal>
                </goals>
                <configuration>
                  <ignoreErrorExitCode>true</ignoreErrorExitCode>
                  <outLogFile>vet.log</outLogFile>
                </configuration>
              </execution>

there are error showing up at the console, but vet.log has a 0-byte size

the same mechanic works for go test

The feature is a tremendous benefit at CI/Jenkins build, use can just view the go vet log instead of the huge jenkins console has which has every thing.

**Comment by raydac** [comment]
vet writes its error into error stream so that it can be saved as `<errLogFile>vet.err.log</errLogFile>`

**Comment by raydac** [comment]
I have added extra warning into maven log about situation if file logging for regular console stream is ON and file logging for error console stream is OFF but there is found text in error stream

**Comment by dantran** [comment]
Thanks for the detailed explanation and the log warning
