### ISSUE TITLE
Trying to make a local package only multi-module project

### ISSUE THREAD

**Issue by InvisibleTech** [raydac/mvn-golang#85]
This is most likely a "me" issue for a project that does not use go modules for the internal packages: [skeleton project](https://github.com/InvisibleTech/integration-tools)

## Issue

Trying to create `maven-go` project with modules for services
and apps using them from command line or rest, all under one parent. I stole heavily from examples and I **do not use go module** for now. I am basically doing multiple **local** modules.

I am certain this is a me thing and not a `maven-go` thing but I am not super adept at implementing maven plugins, so I am not sure where to start.

## Initially if I do the Normal Thing I get Issue

Use `mvn clean install` from parent:

    [INFO] --- mvn-golang-wrapper:2.3.6:test (default-test) @ toolthing ---
    [INFO] Scanning maven dependencies
    [INFO] Prepared command line : bin/go test ./...
    [ERROR] 
    [ERROR] ---------Exec.Err---------
    [ERROR] toolthing.go:4:8: cannot find package "org.fergtest/service" in any of:
    [ERROR] 	/home/jferguson/.mvnGoLang/go1.15.6.linux-amd64/src/org.fergtest/service (from $GOROOT)
    [ERROR] 	/home/jferguson/.mvnGoLang/.go_path/src/org.fergtest/service (from $GOPATH)
    [ERROR] 	/home/jferguson/NonKogCode/golang/integration-tools/toolthing/src/org.fergtest/service
    [ERROR] 	/home/jferguson/NonKogCode/golang/integration-tools/toolthing/bin/.__deps__/service-1.0-SNAPSHOT/src/org.fergtest/service
    [ERROR] 

This error is correct for `toolthing` cannot find `service` where it is looking for it, as shown by tree command:

    $ tree toolthing/bin/.__deps__/
    toolthing/bin/.__deps__/
    └── service-1.0-SNAPSHOT
        └── src
            ├── service.go
            └── service_test.go

    2 directories, 2 files

`toolthing/bin/.__deps__/service-1.0-SNAPSHOT/src/org.fergtest/service` is not the directory structure
under `src`

## Hack To Get toolthing to see service

So if I manually alter the layout under `bin/.__deps__` then all my dreams come true and I can run `mvn test` or anything that triggers test running:

    $ ls toolthing/bin/.__deps__/service-1.0-SNAPSHOT/src/org.fergtest/service/
    service.go  service_test.go

Using `tree on .__deps__` I have:

    toolthing/bin/.__deps__/
    └── service-1.0-SNAPSHOT
        └── src
            └── org.fergtest
                └── service
                    ├── service.go
                    └── service_test.go

    4 directories, 2 files

**Comment by raydac** [comment]
thank you very much for so detailed description and the example project
I am playing with it and may be I am not very advanced in my understanding Golang package work but is it ok that files with package `service` situated just in root of project service? 
if I make such changes
1. __service__: move all service src files into new `src/service` subfiolder
2. __service__: replace `<main>service.go</main>` by `<main>service/service.go</main>`
3. __toolthing__: change line `import org.fergtest/service` to `import service`
then project build becomes green
because it doesn't uses modules,  it knows nothing about org.fergteist

**Comment by InvisibleTech** [comment]
I mean for me that may work. In general we may have no way to do this? Originally, I tried to follow the pattern for the https://github.com/raydac/mvn-golang/tree/master/mvn-golang-examples/mvn-golang-example-maven-module-mix example. However, the issue is my submodules are not published as a go module so the go.mod processing failed to find my service submodule.  I myself am a bit inexperienced in go.mod.  I work in a Java/MVN shop and we are looking to bring in Golang for tools and such.  I will try your work around later and report back here.

**Comment by raydac** [comment]
also you can just include sources of another module directly into go path without dependencies like
```xml
<addToGoPath>
   <serviceSrc>${basedir}/../service/src</serviceSrc>
</addToGoPath>
```

**Comment by InvisibleTech** [comment]
Thanks for all your help. I did get the addToGoPath flavor to work for Maven. However my editor of choice for Golang, VSCode, has a useful plugin that plain doesn't like projects without modules: go.mod I had some hacks including using replace for my local subfolder but in the end making Maven-Go happy and VSCode happy and Go lang command line tools happy had me chasing my tail. Go lang module system really is another beast. I am going to close this issue. Thanks for your advice.

**Comment by fmazoyer** [comment]
@raydac Hello Igor, just as mere curiosity, what is your editor of choice? Thank you :-)
