### ISSUE TITLE
Support for GOARM environment variable

### ISSUE THREAD

**Issue by rosolar** [raydac/mvn-golang#9]
When crosscompiling for ARM, I can set <targetOs> and <targetArch> to set GOOS and GOARCH environment variables, but a similar configuration affecting GOARM is missing. I would like to see that in the next release, as I have to compile for a non-FP ARM, which needs GOARM=5 to be set.

**Comment by raydac** [comment]
since 2.1.1 value for $GOARM can be provided as `<targetArm>5</targetArm>`
