### ISSUE TITLE
mvn clean fails in a multi-module project.

### ISSUE THREAD

**Issue by sankala-dremio** [raydac/mvn-golang#90]
Hi, When using mvn-golang-wrapper, mvn clean fails when there are dependencies on other modules in a multi-module project. This is happening even in the examples in this repo.

The actual issue is due to the fact that dependent artifacts are not available.

The root cause seems to be due to the issue that `com.igormaznitsa.mvngolang.GolangCleanMojo` declares `requiresDependencyResolution = ResolutionScope.COMPILE`.

**Comment by raydac** [comment]
which GoSDK allows reproduce such situation? I am trying to reproduce locally and can't, which GoSDK and OS?

**Comment by sankala-dremio** [comment]
Actually, its not really golang issue, but more of maven and dependency management problem.

Attached an example repro.

running `mvn clean` in the parent project throws the error.

`[ERROR] Failed to execute goal on project mvn-go-test-mix-app: Could not resolve dependencies for project com.igormaznitsa:mvn-go-test-mix-app:mvn-golang:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.igormaznitsa:mvn-go-test-mix-terminal:zip:1.0.0-SNAPSHOT, com.igormaznitsa:mvn-go-test-mix-proxy:zip:1.0.0-SNAPSHOT: Could not find artifact com.igormaznitsa:mvn-go-test-mix-terminal:zip:1.0.0-SNAPSHOT -> [Help 1]`

[repro.tar.gz](https://github.com/raydac/mvn-golang/files/6757990/repro.tar.gz)

**Comment by raydac** [comment]
great! you are right! if start cleaning when artifacts not presented in local repository then it fails. but the problem is deeper than maven and projects are red even with your change, it needs changes in processing of dependencies on level of plugin

**Comment by raydac** [comment]
you can try snapshot

**Comment by sankala-dremio** [comment]
Thank you very much! Really appreciate!.

By the way, the other error is simple to overcome via configuration. Hence didn't suggest a fix for that.

 ```
<build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.igormaznitsa</groupId>
          <artifactId>mvn-golang-wrapper</artifactId>
          <version>${main-project-version}</version>
          <extensions>true</extensions>
          <executions>
            <execution>
              <id>default-clean</id>
              <phase>clean</phase>
              <goals>
                <goal>clean</goal>
              </goals>
              <configuration>
                <scanDependencies>false</scanDependencies>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
```
